---

tool_shed_config_admin_users: "{{ vault_tool_shed_config_admin_users }}"
tool_shed_config_id_secret: "{{ vault_tool_shed_config_id_secret }}"
tool_shed_config_sentry_dsn: "{{ vault_tool_shed_config_sentry_dsn }}"

default_locale: en_US.UTF-8

host_packages:
  - xfsprogs

filesystems:
  - dev: /dev/vdb
    fstype: xfs
    #force: true
  - dev: /dev/vdc
    fstype: xfs
    #force: true

mounts:
  - src: /dev/vdb
    path: /var/lib/postgresql
    fstype: xfs
    mode: "0755"
    #owner: root
    #group: root
  - src: /dev/vdc
    path: /srv
    fstype: xfs
    mode: "0755"
    owner: root
    group: root

host_private_key_users:
  - name: postgres
    keys:
      - key: backup_mts_rsync
        file: id_backup_rsync
      - key: backup_mts_zfs
        file: id_backup_zfs
  - name: shed
    keys:
      - key: backup_mts_rsync
        file: id_backup_rsync
      - key: backup_mts_zfs
        file: id_backup_zfs

host_lines:
  - path: "~{{ tool_shed_user }}/.ssh/known_hosts"
    line: "{{ ssh_host_keys[zfs_backup.tts.server] }}"
    create: true
    mode: "0644"
    owner: "{{ tool_shed_user }}"
    group: "{{ tool_shed_group }}"
  - path: ~postgres/.ssh/known_hosts
    line: "{{ ssh_host_keys[zfs_backup.tts.server] }}"
    create: true
    mode: "0644"
    owner: postgres
    group: postgres

# DB Version: 16
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 12 GB
# CPUs num: 4
# Connections num: 100
# Data Storage: hdd
postgresql_conf:
  max_connections: 100
  shared_buffers: 3GB
  effective_cache_size: 9GB
  maintenance_work_mem: 768MB
  checkpoint_completion_target: 0.9
  wal_buffers: 16MB
  default_statistics_target: 100
  random_page_cost: 4
  effective_io_concurrency: 2
  work_mem: 15728kB
  huge_pages: "off"
  min_wal_size: 1GB
  max_wal_size: 4GB
  max_worker_processes: 4
  max_parallel_workers_per_gather: 2
  max_parallel_workers: 4
  max_parallel_maintenance_workers: 2

postgresql_backup_hour: 3

zfs_backup_profile: "{{ zfs_backup.mts }}"
tool_shed_backup_hour: 2

# When running under the OS Python 3.11, the TS encounters a GPF any time the iuc account attempts to load the UI (after
# login):
#   kernel: traps: gunicorn[370889] general protection fault ip:5001f7 sp:7fa2371fbd00 error:0 in python3.11[41f000+2b3000]
# Originally I thought it was this:
#   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050843
# But the issue still occurs after that upgrade. So just switching to 3.9 for now, we can revisit if 3.11 doesn't work
# for TSv2.
#
# NOTE: I actually installed miniforge by hand, not via ansible, this is just in case everything blows up
miniconda_prefix: /srv/toolshed/main/conda
miniconda_version: 24.3.0
miniconda_conda_environments:
  python@3.9:
    channels:
      - conda-forge
    packages:
      - python=3.9

tool_shed_dbname: tool_shed_main
tool_shed_instance_codename: main
tool_shed_instance_hostname: toolshed.g2.bx.psu.edu
tool_shed_repo: https://github.com/mvdbeek/galaxy.git
tool_shed_version: server_external_hgweb
#tool_shed_version: release_23.1
tool_shed_config_ga_code: "UA-45719423-12"
#tool_shed_api_version: v2
tool_shed_gunicorn_memory_limit: 10G
tool_shed_hgweb_memory_limit: 2G

## used by: error_pages
error_pages_title: "Galaxy Tool Shed"
error_pages_server_name: "The Galaxy Tool Shed"
